name: CD to AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Kubectl
        id: install
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.AZURE_KUBECONFIG }}" > $HOME/.kube/config

      - name: Deploy to AKS
        run: |
          kubectl apply -f k8s/deployment.yaml

      - name: Verify deployment
        run: |
          kubectl rollout status deployment/blog-application
          kubectl get services
