name: Scale Blog Application

on:
  workflow_dispatch:
    inputs:
      replicas:
        description: 'Number of application replicas'
        required: false
        default: '1'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Kubectl
        id: install
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.AZURE_KUBECONFIG }}" > $HOME/.kube/config

      - name: Apply Deployment YAML
        run: |
          echo "Updated deployment to have replicas: ${{ github.event.inputs.replicas }}"
          kubectl scale --replicas=5 deployment/blog-application

      - name: Check number of Pods
        run: |
          kubectl get pods -l app=blog-application -o wide
          echo "Total pods:"
          kubectl get pods -l app=blog-application --no-headers | wc -l

      - name: Verify Rolling Update Status
        run: |
          kubectl rollout status deployment/blog-application

      - name: Final Pod Details
        run: |
          kubectl get pods -l app=blog-application -o wide
